export {
  adminPermissions,
  adminWorkspaces,
  canAccessWorkspace,
  canOwnLeads,
  canPerform,
  canTakeConsultations,
  getDefaultWorkspace,
  getAssignableTeamMembers,
  getFirstAssignableTeamMemberId,
  hasAccess,
  isActiveTeamMember,
  type AdminPermission,
  type AdminWorkspace,
} from './backend/rbac';
